version: "3.9"

services:
  app1:
    image: deirofelippe/teste-tecnico-nimbus-app-1:v1
    build:
      context: ./aplicacao-1
      dockerfile: Dockerfile
    container_name: app1
    ports:
      - 5784:5784
    volumes:
      - "./aplicacao-1:/app"
      - "./Makefile:/app/Makefile"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: teste_nimbus.settings
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "1"
    #       memory: 512M

  app2:
    image: deirofelippe/teste-tecnico-nimbus-app-2:v1
    build:
      context: ./aplicacao-2
      dockerfile: Dockerfile
    container_name: app2
    ports:
      - 3000:3000
    volumes:
      - "./aplicacao-2:/app"
      - "./Makefile:/app/Makefile"
    depends_on:
      - db
      - app1

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    # volumes:
    #   - "./.v_mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: teste_nimbus

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
