version: "3.9"

networks:
  default:
    name: nimbus
    internal: true

services:
  develop-nimbus:
    image: deirofelippe/develop-teste-tecnico-nimbus:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: develop-nimbus
    working_dir: /app/aplicacao-1
    # command: sleep infinity
    # working_dir: /app/aplicacao-2
    ports:
      - 3030:3030
    volumes:
      - "./:/app"

  app1:
    image: deirofelippe/teste-tecnico-nimbus-app-1:latest
    build:
      context: ./aplicacao-1
      dockerfile: Dockerfile
    container_name: app1
    ports:
      - 5784:5784
    volumes:
      - "./:/app"
      - "./Makefile:/app/aplicacao-1/Makefile:ro"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: teste_nimbus.settings
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5784/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

  app2:
    image: deirofelippe/teste-tecnico-nimbus-app-2:latest
    build:
      context: ./aplicacao-2
      dockerfile: Dockerfile
    container_name: app2
    ports:
      - 3000:3000
    volumes:
      - "./:/app"
      - "./Makefile:/app/aplicacao-2/Makefile:ro"
    depends_on:
      db:
        condition: service_healthy
      app1:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    # volumes:
    #   - "./.v_mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: teste_nimbus
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
