# Generated by Django 5.1.1 on 2024-09-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                ("telefone", models.CharField(max_length=50)),
                ("idade", models.IntegerField()),
            ],
        ),
    ]
