# Generated by Django 5.1.1 on 2024-09-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_rename_idade_customer_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=13),
        ),
    ]
