# Generated by Django 5.1.1 on 2024-09-14 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_alter_customer_email_alter_customer_name_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customer",
            table="customers",
        ),
    ]
