# Generated by Django 5.1.1 on 2024-09-13 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="idade",
            new_name="age",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="telefone",
            new_name="phone",
        ),
    ]
